### ISSUE TITLE
Use `REDIS_HOST` environment variable as endpoint while waiting to connect workflow manager to redis at  startup

### ISSUE THREAD

**Issue by pwablito** [openmpf/openmpf-docker#223]
It would be very nice to be able to specify the hostname of the redis server in an environment variable when starting the workflow manager.

It appears there is a `REDIS_HOST` environment variable defined in `workflow_manager/Dockerfile` that is  indeed leveraged as the host to connect to (`trunk/workflow-manager/src/main/resources/applicationContext-redis.xml` in the  openmpf repo). However, this variable is not leveraged in `workflow_manager/docker_entrypoint.sh` line 90 while repeatedly attempting to connect the workflow manager to redis at startup.

It is likely that I am missing something here, please let me know if there is another way to do this.

**Comment by jrobble** [comment]
Thanks for creating an issue and PR for this!
